### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by rcassiau** [rcassiau/SEBC#1]

**Comment by rcassiau** [comment]
**CM Install Lab - Prepare EC2 or other instances : OK**

**Comment by rcassiau** [comment]
**System Configuration Checks : OK**

**Comment by rcassiau** [comment]
**MariaDB Installation Lab : OK**

**Comment by rcassiau** [comment]
**Path B install using Cloudera 5.8.3 : OK**

**Comment by rcassiau** [comment]
**Create a local parcel repo (Bonus) : OK**

**Comment by mfernest** [comment]
🏆
