### ISSUE TITLE
Welcome to SEBC

### ISSUE THREAD

**Issue by mfernest** [rcassiau/SEBC#2]
Your repository setup appears complete and correct.

Please add a comment here with your name. Although some GitHub handles are easy to decipher, enough people use avatar names that we want to be sure of the match.

Regards,

Rob & Michael

**Comment by rsiwicki** [comment]
I have had them all send thier handles and names. Will send the list to you tonight.

**Comment by rcassiau** [comment]
Hello Michael,
My name is Romain Cassiau.
Regards
