### ISSUE TITLE
Storage labs

### ISSUE THREAD

**Issue by rcassiau** [rcassiau/SEBC#3]

**Comment by rcassiau** [comment]
**HDFS Lab: Replicate to another cluster : ISSUE**

Unable to replicate data from colleague cluster to my cluster. 
It's probably due to AWS which block trafic between these clusters or something like that.

I try to replicate data locally with BDR and it works fine.

**Comment by rcassiau** [comment]
**HDFS Lab: Test HDFS Snapshots : OK**

**Comment by rcassiau** [comment]
http://ec2-34-253-82-44.eu-west-1.compute.amazonaws.com:7180/cmf/home

**Comment by mfernest** [comment]
Helpful commenting, thank you.
