### ISSUE TITLE
Security lab

### ISSUE THREAD

**Issue by rcassiau** [rcassiau/SEBC#6]

**Comment by rcassiau** [comment]
**Implement TLS Level 1 Security : OK**

**Comment by rcassiau** [comment]
**Security Labs Preparation : OK**

**Comment by rcassiau** [comment]
**Integrating Kerberos with Cloudera Manager : OK**

**Comment by rcassiau** [comment]
**Sentry Lab : OK**

**Comment by mfernest** [comment]
👍
